#!/bin/bash -e

tmpdir=$(mktemp -d)
trap "rm -r $tmpdir" SIGINT SIGTERM EXIT
virtualenv $tmpdir
source $tmpdir/bin/activate
python2 -m pip install --no-use-wheel --download pypi_download_base $(cat resources_base/python_packages.txt | tr '\n' ' ')

cat <<EOF>tests_base/test_python_packages.sh
#!/bin/bash -e
# This file is generated by tools/03_download_base_python_packages.sh, do not edit.
EOF
for pypkg in $(cat resources-base/python_packages.txt); do
    if [[ $pypkg == *-* ]]; then
        continue
    fi
    echo "python -c \"import $pypkg\"">>tests_base/test_python_packages.sh
done
